"""Generate submission-ready, branded documents from Onus data.

Editable Word (.docx) documents a firm can finalize, file, or hand to an external
evaluator. python-docx is pure-Python so it runs on the serverless runtime; docx symbols
are imported lazily inside the helpers so they only add to cold start when a document is
actually generated.

Every document shares one branded base (Onus seal + wordmark header, recolored headings,
shaded table headers, page-numbered footer) so the output looks designed, not like a raw
Word export. AI-generated prose (the risk summary, policy bodies, SMR grounds) is rendered
through _add_markdown so the model's ## headings, - bullets and **bold** become real Word
structure.
"""
from __future__ import annotations

import io
import os
import re

LOGO_PATH = os.path.join(os.path.dirname(__file__), "assets", "onus-mark.png")

# Brand palette (matches the app: minimalist near-black on white).
_INK = "171717"   # near-black, brand primary
_MUTED = "6B6B6B"  # secondary text
_RULE = "D4D4D4"  # hairline rules / borders
_SHADE = "F4F4F5"  # table header / accent fill


def _rgb(hex6: str):
    from docx.shared import RGBColor

    return RGBColor.from_string(hex6)


def _set_base_styles(doc) -> None:
    from docx.shared import Pt

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = _rgb("262626")
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.12

    sizes = {1: 13, 2: 11.5, 3: 10.5}
    for lvl, size in sizes.items():
        try:
            h = doc.styles[f"Heading {lvl}"]
        except KeyError:
            continue
        h.font.name = "Calibri"
        h.font.bold = True
        h.font.size = Pt(size)
        h.font.color.rgb = _rgb(_INK if lvl < 3 else _MUTED)
        h.paragraph_format.space_before = Pt(10 if lvl == 1 else 8)
        h.paragraph_format.space_after = Pt(3)


def _bottom_border(paragraph, color: str = _RULE, sz: str = "6") -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    pPr = paragraph._p.get_or_add_pPr()
    pbdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), sz)  # eighths of a point
    bottom.set(qn("w:space"), "6")
    bottom.set(qn("w:color"), color)
    pbdr.append(bottom)
    pPr.append(pbdr)


def _field_code(paragraph, instr: str, size: int = 8, color: str = _MUTED) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt

    run = paragraph.add_run()
    run.font.size = Pt(size)
    run.font.color.rgb = _rgb(color)
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr_el = OxmlElement("w:instrText")
    instr_el.set(qn("xml:space"), "preserve")
    instr_el.text = instr
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(instr_el)
    run._r.append(end)


def _shade_cell(cell, fill: str) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), fill)
    tcPr.append(shd)


def _brand_chrome(doc) -> None:
    """Header (seal + wordmark + rule) and footer (disclaimer + page numbers)."""
    from docx.shared import Pt

    section = doc.sections[0]

    header = section.header
    header.is_linked_to_previous = False
    hp = header.paragraphs[0]
    hp.text = ""
    if os.path.exists(LOGO_PATH):
        hp.add_run().add_picture(LOGO_PATH, height=Pt(13))
    mark = hp.add_run("  Onus")
    mark.bold = True
    mark.font.size = Pt(12)
    mark.font.color.rgb = _rgb(_INK)
    tag = hp.add_run("    AML/CTF compliance")
    tag.font.size = Pt(8)
    tag.font.color.rgb = _rgb(_MUTED)
    _bottom_border(hp)

    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.text = ""
    left = fp.add_run("Generated by Onus - not legal advice.    ")
    left.font.size = Pt(8)
    left.font.color.rgb = _rgb(_MUTED)
    page = fp.add_run("Page ")
    page.font.size = Pt(8)
    page.font.color.rgb = _rgb(_MUTED)
    _field_code(fp, "PAGE")
    sep = fp.add_run(" of ")
    sep.font.size = Pt(8)
    sep.font.color.rgb = _rgb(_MUTED)
    _field_code(fp, "NUMPAGES")


def _title_block(doc, title: str, subtitle: str | None) -> None:
    from docx.shared import Pt

    t = doc.add_paragraph()
    t.paragraph_format.space_before = Pt(4)
    t.paragraph_format.space_after = Pt(2)
    tr = t.add_run(title)
    tr.bold = True
    tr.font.size = Pt(20)
    tr.font.color.rgb = _rgb(_INK)
    if subtitle:
        s = doc.add_paragraph()
        s.paragraph_format.space_after = Pt(10)
        sr = s.add_run(subtitle)
        sr.font.size = Pt(11)
        sr.font.color.rgb = _rgb(_MUTED)


def _new_doc(title: str, subtitle: str | None = None):
    from docx import Document

    doc = Document()
    _set_base_styles(doc)
    _brand_chrome(doc)
    _title_block(doc, title, subtitle)
    return doc


def _meta_line(doc, label: str, value: str) -> None:
    """A compact 'Label: value' line for document metadata."""
    p = doc.add_paragraph()
    p.paragraph_format.space_after = None
    lab = p.add_run(f"{label}: ")
    lab.bold = True
    lab.font.color.rgb = _rgb(_INK)
    p.add_run(value)


def _field(doc, label: str, value) -> None:
    p = doc.add_paragraph()
    lab = p.add_run(f"{label}: ")
    lab.bold = True
    lab.font.color.rgb = _rgb(_INK)
    p.add_run(str(value) if value not in (None, "") else "Not specified")


def _disclaimer(doc, text: str) -> None:
    from docx.shared import Pt

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = _rgb(_MUTED)


def _caution(doc, text: str) -> None:
    from docx.shared import Pt

    p = doc.add_paragraph()
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = _rgb(_INK)


def _brand_table(doc, headers: list[str]):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for cell, text in zip(table.rows[0].cells, headers):
        _shade_cell(cell, _SHADE)
        run = cell.paragraphs[0].add_run(text)
        run.bold = True
        run.font.color.rgb = _rgb(_INK)
    return table


_BOLD_RE = re.compile(r"(\*\*[^*]+\*\*)")
_HEAD_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET_RE = re.compile(r"^[-*]\s+")
_NUM_RE = re.compile(r"^\d+\.\s+")
_BLOCK_RE = re.compile(r"^(#{1,6})\s+|^[-*]\s+|^\d+\.\s+")


def _add_inline(paragraph, text: str) -> None:
    for part in _BOLD_RE.split(text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            paragraph.add_run(part[2:-2]).bold = True
        else:
            paragraph.add_run(part)


def _add_markdown(doc, text: str) -> None:
    """Render the lightweight markdown the AI emits (## headings, - bullets, **bold**)
    into proper Word structure. Falls back to plain paragraphs for prose."""
    lines = (text or "").replace("\r", "").split("\n")
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if not stripped:
            i += 1
            continue
        head = _HEAD_RE.match(stripped)
        if head:
            level = min(max(len(head.group(1)), 2), 3)  # keep below the section H1
            h = doc.add_heading("", level=level)
            _add_inline(h, head.group(2))
            i += 1
            continue
        if _BULLET_RE.match(stripped):
            p = doc.add_paragraph(style="List Bullet")
            _add_inline(p, _BULLET_RE.sub("", stripped))
            i += 1
            continue
        if _NUM_RE.match(stripped):
            p = doc.add_paragraph(style="List Number")
            _add_inline(p, _NUM_RE.sub("", stripped))
            i += 1
            continue
        para: list[str] = []
        while i < len(lines) and lines[i].strip() and not _BLOCK_RE.match(lines[i].strip()):
            para.append(lines[i].strip())
            i += 1
        _add_inline(doc.add_paragraph(), " ".join(para))


def _save(doc) -> bytes:
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_risk_assessment_docx(assessment, firm_name: str) -> bytes:
    """Render the current risk assessment as a branded, submission-ready .docx."""
    doc = _new_doc("AML/CTF Risk Assessment", firm_name or "Your firm")

    rating = (assessment.overall_risk_rating or "unassessed").capitalize()
    _meta_line(doc, "Overall ML/TF risk rating", rating)
    method = assessment.methodology or "impact_only"
    tier = assessment.complexity_tier or "low"
    _meta_line(doc, "Methodology", f"{method} ({tier} complexity)")
    if assessment.next_review_due_at:
        _meta_line(doc, "Next review due", str(assessment.next_review_due_at.date()))
    if assessment.approved_by_name and assessment.approved_at:
        _meta_line(
            doc, "Status", f"Approved by {assessment.approved_by_name} on {assessment.approved_at.date()}"
        )
    else:
        _meta_line(doc, "Status", "Draft - pending approval by the senior manager")

    if assessment.summary:
        doc.add_heading("Summary", level=1)
        _add_markdown(doc, assessment.summary)

    def factor_section(title: str, rows, name_attr: str) -> None:
        doc.add_heading(title, level=1)
        rows = list(rows)
        if not rows:
            doc.add_paragraph("None recorded.")
            return
        table = _brand_table(doc, ["Factor", "Inherent risk", "Rationale"])
        for r in rows:
            cells = table.add_row().cells
            cells[0].text = str(getattr(r, name_attr))
            cells[1].text = (r.inherent_risk_rating or "").capitalize()
            cells[2].text = r.explanation or ""

    factor_section("Designated services", assessment.services, "designated_service_type")
    factor_section("Customer types", assessment.customer_types, "customer_type")
    factor_section("Delivery channels", assessment.delivery_channels, "channel_type")

    doc.add_heading("Countries", level=1)
    countries = list(assessment.countries)
    if not countries:
        doc.add_paragraph("No elevated country risk recorded.")
    else:
        table = _brand_table(doc, ["Country", "Inherent risk", "Basis"])
        for c in countries:
            cells = table.add_row().cells
            cells[0].text = c.country
            cells[1].text = (c.inherent_risk_rating or "").capitalize()
            cells[2].text = c.explanation or ""

    doc.add_heading("Proliferation financing", level=1)
    pf_line = "Assessed" if assessment.pf_assessed else "Not yet assessed"
    if assessment.pf_risk_rating:
        pf_line += f" - {assessment.pf_risk_rating.capitalize()} risk"
    doc.add_paragraph(pf_line + ".")
    if assessment.pf_rationale:
        _add_markdown(doc, assessment.pf_rationale)

    _disclaimer(
        doc,
        "Keep this as part of your AML/CTF records and retain it for 7 years; it is not lodged "
        "with AUSTRAC, but produce it on request or during an examination. Generated by Onus to "
        "save you time and is not legal advice; review and approve it before you rely on it.",
    )
    return _save(doc)


def build_smr_docx(*, report, firm_name: str, client_name: str, matter_desc: str) -> bytes:
    """Render a suspicious matter report's prepared content as a branded .docx record. SMRs
    are lodged through AUSTRAC Online, so this is the reviewable content, not a lodgement file."""
    payload = report.payload or {}
    doc = _new_doc("Suspicious Matter Report", firm_name or "Your firm")

    _caution(
        doc,
        "Prepared content for lodgement via AUSTRAC Online. This is your reviewable record - "
        "lodge the report through AUSTRAC's secure channel; do not email it.",
    )

    doc.add_heading("Report details", level=1)
    _field(doc, "Reporting entity", firm_name)
    _field(doc, "Report type", "Suspicious matter report (SMR)")
    _field(doc, "Status", report.status)
    if report.due_at:
        _field(doc, "Reporting deadline", report.due_at.date().isoformat())
    if report.deadline_basis:
        _field(doc, "Deadline basis", report.deadline_basis)
    if report.reference_number:
        _field(doc, "AUSTRAC reference", report.reference_number)

    doc.add_heading("Subject of the report", level=1)
    _field(doc, "Client / customer", client_name)
    _field(doc, "Matter", matter_desc)
    _field(doc, "Indicator observed", payload.get("indicator"))

    doc.add_heading("Grounds for suspicion", level=1)
    grounds = payload.get("grounds_for_suspicion")
    if grounds:
        _add_markdown(doc, grounds)
    else:
        doc.add_paragraph("Not yet drafted.")

    _caution(
        doc,
        "Tipping-off: do not disclose to the customer, or anyone not required to know, that this "
        "report is being prepared or has been lodged (Act s123).",
    )
    _disclaimer(
        doc,
        "Generated by Onus to save you time. This is not legal advice; review and approve it "
        "before lodging.",
    )
    return _save(doc)


def build_program_docx(program, firm_name: str) -> bytes:
    """Render the AML/CTF compliance program (policies + status) as a branded .docx."""
    doc = _new_doc("AML/CTF Compliance Program", firm_name or "Your firm")

    _meta_line(doc, "Status", f"{program.status} (version {program.version})")
    if program.approved_by_name and program.approved_at:
        role = (program.approved_by_role or "").replace("_", " ")
        suffix = f" ({role})" if role else ""
        _meta_line(
            doc, "Approval", f"Approved by {program.approved_by_name}{suffix} on {program.approved_at.date()}"
        )
    else:
        _meta_line(doc, "Approval", "Draft - pending approval by the senior manager")
    if program.next_review_due_at:
        _meta_line(doc, "Next review due", str(program.next_review_due_at.date()))

    doc.add_paragraph(
        "This program documents the policies, procedures, systems and controls this practice "
        "maintains to manage its money laundering, terrorism financing and proliferation "
        "financing risks under the AML/CTF Act 2006."
    )

    for p in sorted(program.policies, key=lambda x: x.title):
        doc.add_heading(p.title, level=1)
        if p.act_reference:
            from docx.shared import Pt

            ref = doc.add_paragraph()
            ref_run = ref.add_run(f"Authority: {p.act_reference}")
            ref_run.italic = True
            ref_run.font.size = Pt(9)
            ref_run.font.color.rgb = _rgb(_MUTED)
        body = (p.body or "").strip()
        if body:
            _add_markdown(doc, body)
        else:
            doc.add_paragraph("Not yet documented.")

    _disclaimer(
        doc,
        "Keep this as part of your AML/CTF records and retain it for 7 years; it is not lodged "
        "with AUSTRAC, but produce it on request or during an examination. Generated by Onus to "
        "save you time and is not legal advice; review and approve it before you rely on it.",
    )
    return _save(doc)


def build_evaluation_docx(evaluation, firm_name: str) -> bytes:
    """Render an independent-evaluation record (status, evaluator, findings, distribution)."""
    e = evaluation
    doc = _new_doc("Independent Evaluation Report", firm_name or "Your firm")

    def datestr(value):
        if value is None:
            return None
        return value.date().isoformat() if callable(getattr(value, "date", None)) else str(value)

    doc.add_heading("Evaluation", level=1)
    _field(doc, "Status", (e.status or "").replace("_", " "))
    _field(doc, "First evaluation", "Yes" if e.is_first_evaluation else "No")
    if e.statutory_deadline:
        _field(doc, "Statutory deadline", datestr(e.statutory_deadline))
    if e.scheduled_for:
        _field(doc, "Scheduled for", datestr(e.scheduled_for))
    _field(doc, "Review frequency", f"{e.frequency_months} months" if e.frequency_months else "Not set")
    if e.frequency_rationale:
        _field(doc, "Frequency rationale", e.frequency_rationale)

    doc.add_heading("Evaluator", level=1)
    if e.evaluator:
        _field(doc, "Name", e.evaluator.name)
        _field(doc, "Type", (e.evaluator.kind or "").replace("_", " "))
        _field(doc, "Independence confirmed", "Yes" if e.evaluator.independence_confirmed else "No")
        if e.evaluator.selection_rationale:
            _field(doc, "Selection rationale", e.evaluator.selection_rationale)
    else:
        doc.add_paragraph("No evaluator assigned yet.")

    doc.add_heading("Findings", level=1)
    findings = list(e.findings)
    if not findings:
        doc.add_paragraph("No findings recorded.")
    else:
        table = _brand_table(doc, ["Area", "Adverse", "Description and remediation", "Status"])
        for f in findings:
            cells = table.add_row().cells
            cells[0].text = f.area or ""
            cells[1].text = "Yes" if f.is_adverse else "No"
            desc = f.description or ""
            if f.remediation_action:
                desc += f"\nRemediation: {f.remediation_action}"
            cells[2].text = desc
            cells[3].text = (f.status or "").replace("_", " ")

    doc.add_heading("Distribution", level=1)
    _field(doc, "To governing body", datestr(e.distributed_to_governing_body_at) or "Not yet")
    _field(doc, "To senior manager", datestr(e.distributed_to_senior_manager_at) or "Not yet")

    _disclaimer(
        doc,
        "Keep this evaluation report on file and provide it to senior management (and the "
        "governing body if applicable); it is not lodged with AUSTRAC. Generated by Onus to save "
        "you time and is not legal advice; review before you rely on it.",
    )
    return _save(doc)
