"""Generate submission-ready documents from Onus data.

Editable Word (.docx) documents a firm can finalize, file, or hand to an external
evaluator. python-docx is pure-Python so it runs on the serverless runtime; docx is
imported lazily inside each builder so it only adds to cold start when a document is
actually generated.
"""
from __future__ import annotations

import io


def build_risk_assessment_docx(assessment, firm_name: str) -> bytes:
    """Render the current risk assessment as a formatted, submission-ready .docx."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    doc.add_heading("AML/CTF Risk Assessment", level=0)
    name = doc.add_paragraph()
    name.add_run(firm_name or "Your firm").bold = True

    overall = doc.add_paragraph()
    overall.add_run("Overall ML/TF risk rating: ").bold = True
    overall.add_run((assessment.overall_risk_rating or "unassessed").capitalize())

    method = assessment.methodology or "impact_only"
    tier = assessment.complexity_tier or "low"
    doc.add_paragraph(f"Methodology: {method} ({tier} complexity).")
    if assessment.next_review_due_at:
        doc.add_paragraph(f"Next review due: {assessment.next_review_due_at.date()}.")
    if assessment.approved_by_name and assessment.approved_at:
        doc.add_paragraph(
            f"Approved by {assessment.approved_by_name} on {assessment.approved_at.date()}."
        )
    else:
        doc.add_paragraph("Status: draft - pending approval by the senior manager.")

    if assessment.summary:
        doc.add_heading("Summary", level=1)
        doc.add_paragraph(assessment.summary)

    def factor_section(title: str, rows, name_attr: str) -> None:
        doc.add_heading(title, level=1)
        rows = list(rows)
        if not rows:
            doc.add_paragraph("None recorded.")
            return
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        head = table.rows[0].cells
        head[0].paragraphs[0].add_run("Factor").bold = True
        head[1].paragraphs[0].add_run("Inherent risk").bold = True
        head[2].paragraphs[0].add_run("Rationale").bold = True
        for r in rows:
            cells = table.add_row().cells
            cells[0].text = str(getattr(r, name_attr))
            cells[1].text = (r.inherent_risk_rating or "").capitalize()
            cells[2].text = r.explanation or ""

    factor_section("Designated services", assessment.services, "designated_service_type")
    factor_section("Customer types", assessment.customer_types, "customer_type")
    factor_section("Delivery channels", assessment.delivery_channels, "channel_type")

    doc.add_heading("Countries", level=1)
    countries = list(assessment.countries)
    if not countries:
        doc.add_paragraph("No elevated country risk recorded.")
    else:
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        head = table.rows[0].cells
        head[0].paragraphs[0].add_run("Country").bold = True
        head[1].paragraphs[0].add_run("Inherent risk").bold = True
        head[2].paragraphs[0].add_run("Basis").bold = True
        for c in countries:
            cells = table.add_row().cells
            cells[0].text = c.country
            cells[1].text = (c.inherent_risk_rating or "").capitalize()
            cells[2].text = c.explanation or ""

    doc.add_heading("Proliferation financing", level=1)
    pf_line = "Assessed" if assessment.pf_assessed else "Not yet assessed"
    if assessment.pf_risk_rating:
        pf_line += f" - {assessment.pf_risk_rating.capitalize()} risk"
    doc.add_paragraph(pf_line + ".")
    if assessment.pf_rationale:
        doc.add_paragraph(assessment.pf_rationale)

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review and approve "
        "it before you rely on it or provide it to AUSTRAC or an external evaluator."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_program_docx(program, firm_name: str) -> bytes:
    """Render the AML/CTF compliance program (policies + status) as a .docx."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    doc.add_heading("AML/CTF Compliance Program", level=0)
    name = doc.add_paragraph()
    name.add_run(firm_name or "Your firm").bold = True

    status = doc.add_paragraph()
    status.add_run("Status: ").bold = True
    status.add_run(f"{program.status} (version {program.version}).")
    if program.approved_by_name and program.approved_at:
        role = (program.approved_by_role or "").replace("_", " ")
        suffix = f" ({role})" if role else ""
        doc.add_paragraph(
            f"Approved by {program.approved_by_name}{suffix} on {program.approved_at.date()}."
        )
    else:
        doc.add_paragraph("Draft - pending approval by the senior manager.")
    if program.next_review_due_at:
        doc.add_paragraph(f"Next review due: {program.next_review_due_at.date()}.")

    doc.add_paragraph(
        "This program documents the policies, procedures, systems and controls this practice "
        "maintains to manage its money laundering, terrorism financing and proliferation "
        "financing risks under the AML/CTF Act 2006."
    )

    for p in sorted(program.policies, key=lambda x: x.title):
        doc.add_heading(p.title, level=1)
        if p.act_reference:
            ref = doc.add_paragraph()
            ref_run = ref.add_run(f"Authority: {p.act_reference}")
            ref_run.italic = True
            ref_run.font.size = Pt(9)
        body = (p.body or "").strip()
        doc.add_paragraph(body if body else "Not yet documented.")

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review and approve "
        "it before you rely on it or provide it to AUSTRAC or an external evaluator."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
