"""Generate submission-ready documents from Onus data.

Editable Word (.docx) documents a firm can finalize, file, or hand to an external
evaluator. python-docx is pure-Python so it runs on the serverless runtime; docx is
imported lazily inside each builder so it only adds to cold start when a document is
actually generated.
"""
from __future__ import annotations

import io
import re


def _plain(text: str) -> str:
    """Strip the lightweight markdown the AI emits (## headings, **bold**) so it reads
    cleanly in the current .docx. The styled-document overhaul renders markdown properly."""
    if not text:
        return text or ""
    out = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.MULTILINE)
    return out.replace("**", "")


def build_risk_assessment_docx(assessment, firm_name: str) -> bytes:
    """Render the current risk assessment as a formatted, submission-ready .docx."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    doc.add_heading("AML/CTF Risk Assessment", level=0)
    name = doc.add_paragraph()
    name.add_run(firm_name or "Your firm").bold = True

    overall = doc.add_paragraph()
    overall.add_run("Overall ML/TF risk rating: ").bold = True
    overall.add_run((assessment.overall_risk_rating or "unassessed").capitalize())

    method = assessment.methodology or "impact_only"
    tier = assessment.complexity_tier or "low"
    doc.add_paragraph(f"Methodology: {method} ({tier} complexity).")
    if assessment.next_review_due_at:
        doc.add_paragraph(f"Next review due: {assessment.next_review_due_at.date()}.")
    if assessment.approved_by_name and assessment.approved_at:
        doc.add_paragraph(
            f"Approved by {assessment.approved_by_name} on {assessment.approved_at.date()}."
        )
    else:
        doc.add_paragraph("Status: draft - pending approval by the senior manager.")

    if assessment.summary:
        doc.add_heading("Summary", level=1)
        doc.add_paragraph(_plain(assessment.summary))

    def factor_section(title: str, rows, name_attr: str) -> None:
        doc.add_heading(title, level=1)
        rows = list(rows)
        if not rows:
            doc.add_paragraph("None recorded.")
            return
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        head = table.rows[0].cells
        head[0].paragraphs[0].add_run("Factor").bold = True
        head[1].paragraphs[0].add_run("Inherent risk").bold = True
        head[2].paragraphs[0].add_run("Rationale").bold = True
        for r in rows:
            cells = table.add_row().cells
            cells[0].text = str(getattr(r, name_attr))
            cells[1].text = (r.inherent_risk_rating or "").capitalize()
            cells[2].text = r.explanation or ""

    factor_section("Designated services", assessment.services, "designated_service_type")
    factor_section("Customer types", assessment.customer_types, "customer_type")
    factor_section("Delivery channels", assessment.delivery_channels, "channel_type")

    doc.add_heading("Countries", level=1)
    countries = list(assessment.countries)
    if not countries:
        doc.add_paragraph("No elevated country risk recorded.")
    else:
        table = doc.add_table(rows=1, cols=3)
        table.style = "Table Grid"
        head = table.rows[0].cells
        head[0].paragraphs[0].add_run("Country").bold = True
        head[1].paragraphs[0].add_run("Inherent risk").bold = True
        head[2].paragraphs[0].add_run("Basis").bold = True
        for c in countries:
            cells = table.add_row().cells
            cells[0].text = c.country
            cells[1].text = (c.inherent_risk_rating or "").capitalize()
            cells[2].text = c.explanation or ""

    doc.add_heading("Proliferation financing", level=1)
    pf_line = "Assessed" if assessment.pf_assessed else "Not yet assessed"
    if assessment.pf_risk_rating:
        pf_line += f" - {assessment.pf_risk_rating.capitalize()} risk"
    doc.add_paragraph(pf_line + ".")
    if assessment.pf_rationale:
        doc.add_paragraph(assessment.pf_rationale)

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review and approve "
        "it before you rely on it or provide it to AUSTRAC or an external evaluator."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_smr_docx(*, report, firm_name: str, client_name: str, matter_desc: str) -> bytes:
    """Render a suspicious matter report's prepared content as a .docx record. SMRs are
    lodged through AUSTRAC Online, so this is the reviewable content, not a lodgement
    file."""
    from docx import Document
    from docx.shared import Pt

    payload = report.payload or {}
    doc = Document()
    doc.add_heading("Suspicious Matter Report (SMR)", level=0)

    note = doc.add_paragraph()
    note_run = note.add_run(
        "Prepared content for lodgement via AUSTRAC Online. This is your reviewable record - "
        "lodge the report through AUSTRAC's secure channel; do not email it."
    )
    note_run.italic = True
    note_run.font.size = Pt(9)

    def field(label: str, value) -> None:
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(str(value) if value else "Not specified")

    doc.add_heading("Reporting entity", level=1)
    field("Reporting entity", firm_name)

    doc.add_heading("Report details", level=1)
    field("Report type", "Suspicious matter report (SMR)")
    field("Status", report.status)
    if report.due_at:
        field("Reporting deadline", report.due_at.date().isoformat())
    if report.deadline_basis:
        field("Deadline basis", report.deadline_basis)
    if report.reference_number:
        field("AUSTRAC reference", report.reference_number)

    doc.add_heading("Subject of the report", level=1)
    field("Client / customer", client_name)
    field("Matter", matter_desc)
    field("Indicator observed", payload.get("indicator"))

    doc.add_heading("Grounds for suspicion", level=1)
    doc.add_paragraph(payload.get("grounds_for_suspicion") or "Not yet drafted.")

    caution = doc.add_paragraph()
    caution_run = caution.add_run(
        "Tipping-off: do not disclose to the customer, or anyone not required to know, that this "
        "report is being prepared or has been lodged (Act s123)."
    )
    caution_run.italic = True
    caution_run.font.size = Pt(9)

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review and approve it "
        "before lodging."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_program_docx(program, firm_name: str) -> bytes:
    """Render the AML/CTF compliance program (policies + status) as a .docx."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    doc.add_heading("AML/CTF Compliance Program", level=0)
    name = doc.add_paragraph()
    name.add_run(firm_name or "Your firm").bold = True

    status = doc.add_paragraph()
    status.add_run("Status: ").bold = True
    status.add_run(f"{program.status} (version {program.version}).")
    if program.approved_by_name and program.approved_at:
        role = (program.approved_by_role or "").replace("_", " ")
        suffix = f" ({role})" if role else ""
        doc.add_paragraph(
            f"Approved by {program.approved_by_name}{suffix} on {program.approved_at.date()}."
        )
    else:
        doc.add_paragraph("Draft - pending approval by the senior manager.")
    if program.next_review_due_at:
        doc.add_paragraph(f"Next review due: {program.next_review_due_at.date()}.")

    doc.add_paragraph(
        "This program documents the policies, procedures, systems and controls this practice "
        "maintains to manage its money laundering, terrorism financing and proliferation "
        "financing risks under the AML/CTF Act 2006."
    )

    for p in sorted(program.policies, key=lambda x: x.title):
        doc.add_heading(p.title, level=1)
        if p.act_reference:
            ref = doc.add_paragraph()
            ref_run = ref.add_run(f"Authority: {p.act_reference}")
            ref_run.italic = True
            ref_run.font.size = Pt(9)
        body = (p.body or "").strip()
        doc.add_paragraph(_plain(body) if body else "Not yet documented.")

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review and approve "
        "it before you rely on it or provide it to AUSTRAC or an external evaluator."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_evaluation_docx(evaluation, firm_name: str) -> bytes:
    """Render an independent-evaluation record (status, evaluator, findings, distribution)."""
    from docx import Document
    from docx.shared import Pt

    e = evaluation
    doc = Document()
    doc.add_heading("Independent Evaluation Report", level=0)
    name = doc.add_paragraph()
    name.add_run(firm_name or "Your firm").bold = True

    def field(label: str, value) -> None:
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(str(value) if value not in (None, "") else "Not specified")

    def datestr(value):
        if value is None:
            return None
        return value.date().isoformat() if callable(getattr(value, "date", None)) else str(value)

    doc.add_heading("Evaluation", level=1)
    field("Status", (e.status or "").replace("_", " "))
    field("First evaluation", "Yes" if e.is_first_evaluation else "No")
    if e.statutory_deadline:
        field("Statutory deadline", datestr(e.statutory_deadline))
    if e.scheduled_for:
        field("Scheduled for", datestr(e.scheduled_for))
    field("Review frequency", f"{e.frequency_months} months" if e.frequency_months else "Not set")
    if e.frequency_rationale:
        field("Frequency rationale", e.frequency_rationale)

    doc.add_heading("Evaluator", level=1)
    if e.evaluator:
        field("Name", e.evaluator.name)
        field("Type", (e.evaluator.kind or "").replace("_", " "))
        field("Independence confirmed", "Yes" if e.evaluator.independence_confirmed else "No")
        if e.evaluator.selection_rationale:
            field("Selection rationale", e.evaluator.selection_rationale)
    else:
        doc.add_paragraph("No evaluator assigned yet.")

    doc.add_heading("Findings", level=1)
    findings = list(e.findings)
    if not findings:
        doc.add_paragraph("No findings recorded.")
    else:
        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        head = table.rows[0].cells
        head[0].paragraphs[0].add_run("Area").bold = True
        head[1].paragraphs[0].add_run("Adverse").bold = True
        head[2].paragraphs[0].add_run("Description and remediation").bold = True
        head[3].paragraphs[0].add_run("Status").bold = True
        for f in findings:
            cells = table.add_row().cells
            cells[0].text = f.area or ""
            cells[1].text = "Yes" if f.is_adverse else "No"
            desc = f.description or ""
            if f.remediation_action:
                desc += f"\nRemediation: {f.remediation_action}"
            cells[2].text = desc
            cells[3].text = (f.status or "").replace("_", " ")

    doc.add_heading("Distribution", level=1)
    field("To governing body", datestr(e.distributed_to_governing_body_at) or "Not yet")
    field("To senior manager", datestr(e.distributed_to_senior_manager_at) or "Not yet")

    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Generated by Onus to save you time. This is not legal advice; review before you rely "
        "on it or distribute it."
    )
    run.italic = True
    run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
