"""Generate branded, submission-ready PDF documents - the PDF counterpart to docgen.py.

reportlab is pure-Python so it runs on the serverless runtime; its symbols are imported
lazily inside the builders to keep cold start low. Every PDF shares one branded template
(Onus seal + wordmark header, hairline rules, a colored rating block, shaded/zebra tables,
a page-numbered footer) and renders AI prose through a markdown pass, mirroring the Word
output so a firm can pick either format.
"""
from __future__ import annotations

import html
import io
import os
import re

LOGO_PATH = os.path.join(os.path.dirname(__file__), "assets", "onus-mark.png")

_INK = "#171717"
_MUTED = "#6B6B6B"
_RULE = "#D4D4D4"
_SHADE = "#F4F4F5"
_ZEBRA = "#FAFAFA"
_RATING = {"high": "#DC2626", "medium": "#D97706", "low": "#059669", "unassessed": "#6B6B6B"}


def _inline(text: str) -> str:
    """Escape text for reportlab's mini-markup, then turn **bold** into <b>."""
    out = html.escape(text or "")
    return re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)


def _styles():
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    base = getSampleStyleSheet()
    body = ParagraphStyle(
        "OnusBody", parent=base["BodyText"], fontName="Helvetica", fontSize=9.5, leading=13.5,
        textColor=colors.HexColor("#262626"), spaceAfter=5,
    )
    return {
        "body": body,
        "title": ParagraphStyle("OnusTitle", fontName="Helvetica-Bold", fontSize=21, leading=24,
                                 textColor=colors.HexColor(_INK), spaceAfter=2),
        "subtitle": ParagraphStyle("OnusSub", fontName="Helvetica", fontSize=11,
                                    textColor=colors.HexColor(_MUTED), spaceAfter=12),
        "h1": ParagraphStyle("OnusH1", fontName="Helvetica-Bold", fontSize=12.5, leading=15,
                             textColor=colors.HexColor(_INK), spaceBefore=14, spaceAfter=4),
        "h2": ParagraphStyle("OnusH2", fontName="Helvetica-Bold", fontSize=10.5, leading=13,
                             textColor=colors.HexColor(_INK), spaceBefore=8, spaceAfter=3),
        "meta": ParagraphStyle("OnusMeta", parent=body, spaceAfter=1.5),
        "small": ParagraphStyle("OnusSmall", fontName="Helvetica-Oblique", fontSize=8,
                                textColor=colors.HexColor(_MUTED), spaceBefore=12, leading=11),
        "ratepill": ParagraphStyle("OnusRate", fontName="Helvetica-Bold", fontSize=11.5,
                                   textColor=colors.white, leading=14),
    }


def _decorate(canvas, doc):
    """Header (seal + wordmark + rule) and footer (rule + disclaimer + page number)."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm

    w, h = A4
    canvas.saveState()
    if os.path.exists(LOGO_PATH):
        canvas.drawImage(LOGO_PATH, doc.leftMargin, h - 18 * mm, width=7 * mm, height=7 * mm, mask="auto")
    canvas.setFont("Helvetica-Bold", 11)
    canvas.setFillColor(colors.HexColor(_INK))
    canvas.drawString(doc.leftMargin + 9 * mm, h - 16.2 * mm, "Onus")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor(_MUTED))
    canvas.drawString(doc.leftMargin + 20 * mm, h - 16.2 * mm, "AML/CTF compliance")
    canvas.setStrokeColor(colors.HexColor(_RULE))
    canvas.setLineWidth(0.5)
    canvas.line(doc.leftMargin, h - 20 * mm, w - doc.rightMargin, h - 20 * mm)

    canvas.line(doc.leftMargin, 16 * mm, w - doc.rightMargin, 16 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor(_MUTED))
    canvas.drawString(doc.leftMargin, 12 * mm, "Generated by Onus - not legal advice.")
    canvas.drawRightString(w - doc.rightMargin, 12 * mm, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def _meta(st, label: str, value) -> "object":
    val = str(value) if value not in (None, "") else "Not specified"
    return _para(f"<b>{html.escape(label)}:</b> {html.escape(val)}", st["meta"])


def _para(markup: str, style):
    from reportlab.platypus import Paragraph

    return Paragraph(markup, style)


def _rating_block(st, rating: str):
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle

    cap = (rating or "unassessed").capitalize()
    color = _RATING.get((rating or "unassessed").lower(), _MUTED)
    cell = _para(f"Overall ML/TF risk rating: {html.escape(cap)}", st["ratepill"])
    t = Table([[cell]])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(color)),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                ("TOPPADDING", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
            ]
        )
    )
    return t


def _table(st, headers: list, rows: list, col_widths=None):
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Table, TableStyle

    th = ParagraphStyle("th", parent=st["body"], fontName="Helvetica-Bold",
                        textColor=colors.HexColor(_INK))
    data = [[_para(_inline(str(h)), th) for h in headers]]
    for row in rows:
        data.append([_para(_inline(str(c)), st["body"]) for c in row])
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(_SHADE)),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor(_RULE)),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for r in range(2, len(data), 2):
        style.append(("BACKGROUND", (0, r), (-1, r), colors.HexColor(_ZEBRA)))
    t.setStyle(TableStyle(style))
    return t


def _markdown(st, text: str) -> list:
    """Render the AI's lightweight markdown (## headings, - bullets, **bold**) as flowables."""
    from reportlab.platypus import ListFlowable, ListItem

    flow: list = []
    bullets: list = []

    def flush():
        nonlocal bullets
        if bullets:
            flow.append(
                ListFlowable(
                    [ListItem(_para(_inline(b), st["body"]), leftIndent=12) for b in bullets],
                    bulletType="bullet", start="-", bulletFontSize=7, leftIndent=10,
                )
            )
            bullets = []

    lines = (text or "").replace("\r", "").split("\n")
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        if not s:
            flush()
            i += 1
            continue
        head = re.match(r"^(#{1,6})\s+(.*)$", s)
        if head:
            flush()
            flow.append(_para(_inline(head.group(2)), st["h2"]))
            i += 1
            continue
        if re.match(r"^[-*]\s+", s):
            bullets.append(re.sub(r"^[-*]\s+", "", s))
            i += 1
            continue
        flush()
        para = []
        while i < len(lines) and lines[i].strip() and not re.match(r"^(#{1,6})\s+|^[-*]\s+", lines[i].strip()):
            para.append(lines[i].strip())
            i += 1
        flow.append(_para(_inline(" ".join(para)), st["body"]))
    flush()
    return flow


def _build(title: str, subtitle: str, flowables: list) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=26 * mm, bottomMargin=22 * mm, title=title, author="Onus",
    )
    st = _styles()
    story = [_para(_inline(title), st["title"])]
    if subtitle:
        story.append(_para(_inline(subtitle), st["subtitle"]))
    story.extend(flowables)
    doc.build(story, onFirstPage=_decorate, onLaterPages=_decorate)
    return buf.getvalue()


def _disclaimer(st, text: str):
    from reportlab.platypus import Spacer

    return [Spacer(1, 6), _para(_inline(text), st["small"])]


def _heading(st, text: str):
    return _para(_inline(text), st["h1"])


def build_risk_assessment_pdf(assessment, firm_name: str) -> bytes:
    from reportlab.platypus import Spacer

    st = _styles()
    f: list = [_rating_block(st, assessment.overall_risk_rating), Spacer(1, 8)]
    method = assessment.methodology or "impact_only"
    tier = assessment.complexity_tier or "low"
    f.append(_meta(st, "Methodology", f"{method} ({tier} complexity)"))
    if assessment.next_review_due_at:
        f.append(_meta(st, "Next review due", str(assessment.next_review_due_at.date())))
    if assessment.approved_by_name and assessment.approved_at:
        f.append(_meta(st, "Status", f"Approved by {assessment.approved_by_name} on {assessment.approved_at.date()}"))
    else:
        f.append(_meta(st, "Status", "Draft - pending approval by the senior manager"))

    if assessment.summary:
        f.append(_heading(st, "Summary"))
        f.extend(_markdown(st, assessment.summary))

    def section(title, rows, attr):
        f.append(_heading(st, title))
        rows = list(rows)
        if not rows:
            f.append(_para("None recorded.", st["body"]))
            return
        f.append(
            _table(st, ["Factor", "Inherent risk", "Rationale"],
                   [[str(getattr(r, attr)), (r.inherent_risk_rating or "").capitalize(), r.explanation or ""] for r in rows],
                   col_widths=[150, 75, 245])
        )

    section("Designated services", assessment.services, "designated_service_type")
    section("Customer types", assessment.customer_types, "customer_type")
    section("Delivery channels", assessment.delivery_channels, "channel_type")

    f.append(_heading(st, "Countries"))
    countries = list(assessment.countries)
    if not countries:
        f.append(_para("No elevated country risk recorded.", st["body"]))
    else:
        f.append(
            _table(st, ["Country", "Inherent risk", "Basis"],
                   [[c.country, (c.inherent_risk_rating or "").capitalize(), c.explanation or ""] for c in countries],
                   col_widths=[150, 75, 245])
        )

    f.append(_heading(st, "Proliferation financing"))
    pf = "Assessed" if assessment.pf_assessed else "Not yet assessed"
    if assessment.pf_risk_rating:
        pf += f" - {assessment.pf_risk_rating.capitalize()} risk"
    f.append(_para(_inline(pf + "."), st["body"]))
    if assessment.pf_rationale:
        f.extend(_markdown(st, assessment.pf_rationale))

    f.extend(_disclaimer(st, "Generated by Onus to save you time. This is not legal advice; review "
                             "and approve it before you rely on it or provide it to AUSTRAC or an "
                             "external evaluator."))
    return _build("AML/CTF Risk Assessment", firm_name or "Your firm", f)


def build_smr_pdf(*, report, firm_name: str, client_name: str, matter_desc: str) -> bytes:
    st = _styles()
    payload = report.payload or {}
    f: list = [_para(_inline("Prepared content for lodgement via AUSTRAC Online. This is your "
                             "reviewable record - lodge the report through AUSTRAC's secure channel; "
                             "do not email it."), st["small"])]

    f.append(_heading(st, "Report details"))
    f.append(_meta(st, "Reporting entity", firm_name))
    f.append(_meta(st, "Report type", "Suspicious matter report (SMR)"))
    f.append(_meta(st, "Status", report.status))
    if report.due_at:
        f.append(_meta(st, "Reporting deadline", report.due_at.date().isoformat()))
    if report.deadline_basis:
        f.append(_meta(st, "Deadline basis", report.deadline_basis))
    if report.reference_number:
        f.append(_meta(st, "AUSTRAC reference", report.reference_number))

    f.append(_heading(st, "Subject of the report"))
    f.append(_meta(st, "Client / customer", client_name))
    f.append(_meta(st, "Matter", matter_desc))
    f.append(_meta(st, "Indicator observed", payload.get("indicator")))

    f.append(_heading(st, "Grounds for suspicion"))
    grounds = payload.get("grounds_for_suspicion")
    f.extend(_markdown(st, grounds) if grounds else [_para("Not yet drafted.", st["body"])])

    f.append(_para(_inline("Tipping-off: do not disclose to the customer, or anyone not required to "
                           "know, that this report is being prepared or has been lodged (Act s123)."),
                   st["small"]))
    f.extend(_disclaimer(st, "Generated by Onus to save you time. This is not legal advice; review "
                             "and approve it before lodging."))
    return _build("Suspicious Matter Report", firm_name or "Your firm", f)


def build_program_pdf(program, firm_name: str) -> bytes:
    st = _styles()
    f: list = [_meta(st, "Status", f"{program.status} (version {program.version})")]
    if program.approved_by_name and program.approved_at:
        role = (program.approved_by_role or "").replace("_", " ")
        suffix = f" ({role})" if role else ""
        f.append(_meta(st, "Approval", f"Approved by {program.approved_by_name}{suffix} on {program.approved_at.date()}"))
    else:
        f.append(_meta(st, "Approval", "Draft - pending approval by the senior manager"))
    if program.next_review_due_at:
        f.append(_meta(st, "Next review due", str(program.next_review_due_at.date())))

    f.append(_para("This program documents the policies, procedures, systems and controls this "
                   "practice maintains to manage its money laundering, terrorism financing and "
                   "proliferation financing risks under the AML/CTF Act 2006.", st["body"]))

    for p in sorted(program.policies, key=lambda x: x.title):
        f.append(_heading(st, p.title))
        if p.act_reference:
            f.append(_para(_inline(f"Authority: {p.act_reference}"), st["small"]))
        body = (p.body or "").strip()
        f.extend(_markdown(st, body) if body else [_para("Not yet documented.", st["body"])])

    f.extend(_disclaimer(st, "Generated by Onus to save you time. This is not legal advice; review "
                             "and approve it before you rely on it or provide it to AUSTRAC or an "
                             "external evaluator."))
    return _build("AML/CTF Compliance Program", firm_name or "Your firm", f)


def build_evaluation_pdf(evaluation, firm_name: str) -> bytes:
    st = _styles()
    e = evaluation

    def datestr(value):
        if value is None:
            return None
        return value.date().isoformat() if callable(getattr(value, "date", None)) else str(value)

    f: list = [_heading(st, "Evaluation")]
    f.append(_meta(st, "Status", (e.status or "").replace("_", " ")))
    f.append(_meta(st, "First evaluation", "Yes" if e.is_first_evaluation else "No"))
    if e.statutory_deadline:
        f.append(_meta(st, "Statutory deadline", datestr(e.statutory_deadline)))
    if e.scheduled_for:
        f.append(_meta(st, "Scheduled for", datestr(e.scheduled_for)))
    f.append(_meta(st, "Review frequency", f"{e.frequency_months} months" if e.frequency_months else "Not set"))
    if e.frequency_rationale:
        f.append(_meta(st, "Frequency rationale", e.frequency_rationale))

    f.append(_heading(st, "Evaluator"))
    if e.evaluator:
        f.append(_meta(st, "Name", e.evaluator.name))
        f.append(_meta(st, "Type", (e.evaluator.kind or "").replace("_", " ")))
        f.append(_meta(st, "Independence confirmed", "Yes" if e.evaluator.independence_confirmed else "No"))
        if e.evaluator.selection_rationale:
            f.append(_meta(st, "Selection rationale", e.evaluator.selection_rationale))
    else:
        f.append(_para("No evaluator assigned yet.", st["body"]))

    f.append(_heading(st, "Findings"))
    findings = list(e.findings)
    if not findings:
        f.append(_para("No findings recorded.", st["body"]))
    else:
        rows = []
        for fi in findings:
            desc = fi.description or ""
            if fi.remediation_action:
                desc += f"\nRemediation: {fi.remediation_action}"
            rows.append([fi.area or "", "Yes" if fi.is_adverse else "No", desc, (fi.status or "").replace("_", " ")])
        f.append(_table(st, ["Area", "Adverse", "Description and remediation", "Status"], rows,
                        col_widths=[90, 50, 250, 80]))

    f.append(_heading(st, "Distribution"))
    f.append(_meta(st, "To governing body", datestr(e.distributed_to_governing_body_at) or "Not yet"))
    f.append(_meta(st, "To senior manager", datestr(e.distributed_to_senior_manager_at) or "Not yet"))

    f.extend(_disclaimer(st, "Generated by Onus to save you time. This is not legal advice; review "
                             "before you rely on it or distribute it."))
    return _build("Independent Evaluation Report", firm_name or "Your firm", f)
