"""monitoring alerts

Revision ID: 1cf1584410e1
Revises: d785809592a4
Create Date: 2026-06-01 12:39:23.186186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf1584410e1'
down_revision: Union[str, Sequence[str], None] = 'd785809592a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('indicator_key', sa.String(), nullable=False),
    sa.Column('indicator_group', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), server_default='medium', nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('smr_report_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['smr_report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_client_id'), 'monitoring_alerts', ['client_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_firm_id'), 'monitoring_alerts', ['firm_id'], unique=False)
    op.add_column('reports', sa.Column('related_alert_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'monitoring_alerts', ['related_alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'related_alert_id')
    op.drop_index(op.f('ix_monitoring_alerts_firm_id'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_client_id'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    # ### end Alembic commands ###
