"""compliance program tables

Revision ID: 6122230d1542
Revises: 6a3db11a277c
Create Date: 2026-06-01 11:35:55.773186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6122230d1542'
down_revision: Union[str, Sequence[str], None] = '6a3db11a277c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('documented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_name', sa.String(), nullable=True),
    sa.Column('approved_by_role', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_programs_firm_id'), 'aml_programs', ['firm_id'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('area_key', sa.String(), nullable=False),
    sa.Column('obligation_key', sa.String(), nullable=True),
    sa.Column('act_reference', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['aml_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_firm_id'), 'policies', ['firm_id'], unique=False)
    op.create_index(op.f('ix_policies_program_id'), 'policies', ['program_id'], unique=False)
    op.add_column('governance_approvals', sa.Column('subject_type', sa.String(), nullable=True))
    op.add_column('governance_approvals', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.add_column('governance_approvals', sa.Column('escalation_reason', sa.Text(), nullable=True))
    op.add_column('governance_approvals', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('governance_approvals', sa.Column('approver_name', sa.String(), nullable=True))
    op.add_column('governance_approvals', sa.Column('approver_role', sa.String(), nullable=True))
    op.add_column('governance_approvals', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('governance_approvals', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('governance_approvals', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'governance_approvals', 'users', ['approved_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'governance_approvals', type_='foreignkey')
    op.drop_column('governance_approvals', 'decision_reason')
    op.drop_column('governance_approvals', 'decision')
    op.drop_column('governance_approvals', 'decided_at')
    op.drop_column('governance_approvals', 'approver_role')
    op.drop_column('governance_approvals', 'approver_name')
    op.drop_column('governance_approvals', 'approved_by_user_id')
    op.drop_column('governance_approvals', 'escalation_reason')
    op.drop_column('governance_approvals', 'subject_id')
    op.drop_column('governance_approvals', 'subject_type')
    op.drop_index(op.f('ix_policies_program_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_firm_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_aml_programs_firm_id'), table_name='aml_programs')
    op.drop_table('aml_programs')
    # ### end Alembic commands ###
