"""clients and matters tables

Revision ID: 64479f6a1f68
Revises: 6122230d1542
Create Date: 2026-06-01 11:47:29.471338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64479f6a1f68'
down_revision: Union[str, Sequence[str], None] = '6122230d1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('risk_rating', sa.String(), nullable=True),
    sa.Column('cdd_status', sa.String(), server_default='not_started', nullable=False),
    sa.Column('is_pep', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pep_kind', sa.String(), nullable=True),
    sa.Column('sanctions_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('adverse_media_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_of_funds', sa.Text(), nullable=True),
    sa.Column('source_of_wealth', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_firm_id'), 'clients', ['firm_id'], unique=False)
    op.create_table('client_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bo_basis', sa.String(), nullable=True),
    sa.Column('ownership_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_individual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_pep', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pep_kind', sa.String(), nullable=True),
    sa.Column('sanctions_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('steps_recorded', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_parties_client_id'), 'client_parties', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_parties_firm_id'), 'client_parties', ['firm_id'], unique=False)
    op.create_table('matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('designated_service_key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cdd_gate_passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cdd_gate_basis', sa.String(), nullable=True),
    sa.Column('risk_rating', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matters_client_id'), 'matters', ['client_id'], unique=False)
    op.create_index(op.f('ix_matters_firm_id'), 'matters', ['firm_id'], unique=False)
    op.create_table('cdd_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('kyc_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edd_reason', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), server_default='pending', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdd_checks_client_id'), 'cdd_checks', ['client_id'], unique=False)
    op.create_index(op.f('ix_cdd_checks_firm_id'), 'cdd_checks', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cdd_checks_firm_id'), table_name='cdd_checks')
    op.drop_index(op.f('ix_cdd_checks_client_id'), table_name='cdd_checks')
    op.drop_table('cdd_checks')
    op.drop_index(op.f('ix_matters_firm_id'), table_name='matters')
    op.drop_index(op.f('ix_matters_client_id'), table_name='matters')
    op.drop_table('matters')
    op.drop_index(op.f('ix_client_parties_firm_id'), table_name='client_parties')
    op.drop_index(op.f('ix_client_parties_client_id'), table_name='client_parties')
    op.drop_table('client_parties')
    op.drop_index(op.f('ix_clients_firm_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
