"""risk profile enhancements

Revision ID: 6a3db11a277c
Revises: cbb64de0267d
Create Date: 2026-06-01 11:17:33.749793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3db11a277c'
down_revision: Union[str, Sequence[str], None] = 'cbb64de0267d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('austrac_communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('communicated_on', sa.Date(), nullable=True),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('change_made', sa.Text(), nullable=True),
    sa.Column('considered_on', sa.Date(), nullable=True),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('review_trigger_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['review_trigger_id'], ['review_triggers.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_austrac_communications_firm_id'), 'austrac_communications', ['firm_id'], unique=False)
    op.add_column('risk_assessment_countries', sa.Column('basel_score', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('risk_assessment_countries', sa.Column('fatf_listed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_countries', sa.Column('sanctions_listed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_countries', sa.Column('prescribed_foreign_country', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_countries', sa.Column('tax_haven', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_countries', sa.Column('terrorism_support', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_customer_types', sa.Column('likelihood', sa.String(), nullable=True))
    op.add_column('risk_assessment_customer_types', sa.Column('impact', sa.String(), nullable=True))
    op.add_column('risk_assessment_customer_types', sa.Column('data_source', sa.Text(), nullable=True))
    op.add_column('risk_assessment_customer_types', sa.Column('is_planned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_delivery_channels', sa.Column('likelihood', sa.String(), nullable=True))
    op.add_column('risk_assessment_delivery_channels', sa.Column('impact', sa.String(), nullable=True))
    op.add_column('risk_assessment_delivery_channels', sa.Column('data_source', sa.Text(), nullable=True))
    op.add_column('risk_assessment_delivery_channels', sa.Column('is_planned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessment_services', sa.Column('likelihood', sa.String(), nullable=True))
    op.add_column('risk_assessment_services', sa.Column('impact', sa.String(), nullable=True))
    op.add_column('risk_assessment_services', sa.Column('data_source', sa.Text(), nullable=True))
    op.add_column('risk_assessment_services', sa.Column('is_planned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessments', sa.Column('methodology', sa.String(), server_default='impact_only', nullable=False))
    op.add_column('risk_assessments', sa.Column('complexity_tier', sa.String(), server_default='low', nullable=False))
    op.add_column('risk_assessments', sa.Column('pf_assessed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('risk_assessments', sa.Column('pf_risk_rating', sa.String(), nullable=True))
    op.add_column('risk_assessments', sa.Column('pf_rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_assessments', 'pf_rationale')
    op.drop_column('risk_assessments', 'pf_risk_rating')
    op.drop_column('risk_assessments', 'pf_assessed')
    op.drop_column('risk_assessments', 'complexity_tier')
    op.drop_column('risk_assessments', 'methodology')
    op.drop_column('risk_assessment_services', 'is_planned')
    op.drop_column('risk_assessment_services', 'data_source')
    op.drop_column('risk_assessment_services', 'impact')
    op.drop_column('risk_assessment_services', 'likelihood')
    op.drop_column('risk_assessment_delivery_channels', 'is_planned')
    op.drop_column('risk_assessment_delivery_channels', 'data_source')
    op.drop_column('risk_assessment_delivery_channels', 'impact')
    op.drop_column('risk_assessment_delivery_channels', 'likelihood')
    op.drop_column('risk_assessment_customer_types', 'is_planned')
    op.drop_column('risk_assessment_customer_types', 'data_source')
    op.drop_column('risk_assessment_customer_types', 'impact')
    op.drop_column('risk_assessment_customer_types', 'likelihood')
    op.drop_column('risk_assessment_countries', 'terrorism_support')
    op.drop_column('risk_assessment_countries', 'tax_haven')
    op.drop_column('risk_assessment_countries', 'prescribed_foreign_country')
    op.drop_column('risk_assessment_countries', 'sanctions_listed')
    op.drop_column('risk_assessment_countries', 'fatf_listed')
    op.drop_column('risk_assessment_countries', 'basel_score')
    op.drop_index(op.f('ix_austrac_communications_firm_id'), table_name='austrac_communications')
    op.drop_table('austrac_communications')
    # ### end Alembic commands ###
