"""governance role eligibility

Revision ID: 6a7e2ea6b4ea
Revises: 9d60fce7110c
Create Date: 2026-06-01 14:23:18.021282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7e2ea6b4ea'
down_revision: Union[str, Sequence[str], None] = '9d60fce7110c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('governance_roles', sa.Column('management_level', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('governance_roles', sa.Column('is_australian_resident', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('governance_roles', sa.Column('fit_and_proper_considered', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('governance_roles', sa.Column('qualifies_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('governance_roles', 'qualifies_reason')
    op.drop_column('governance_roles', 'fit_and_proper_considered')
    op.drop_column('governance_roles', 'is_australian_resident')
    op.drop_column('governance_roles', 'management_level')
    # ### end Alembic commands ###
