"""program change log

Revision ID: 9d60fce7110c
Revises: 1cf1584410e1
Create Date: 2026-06-01 14:13:50.767450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d60fce7110c'
down_revision: Union[str, Sequence[str], None] = '1cf1584410e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(), server_default='other', nullable=False),
    sa.Column('is_material', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('documented', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('governing_body_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['governance_approvals.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_change_logs_firm_id'), 'program_change_logs', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_change_logs_firm_id'), table_name='program_change_logs')
    op.drop_table('program_change_logs')
    # ### end Alembic commands ###
