"""reporting and records tables

Revision ID: b2575e44740b
Revises: 64479f6a1f68
Create Date: 2026-06-01 11:59:31.625212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2575e44740b'
down_revision: Union[str, Sequence[str], None] = '64479f6a1f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('retention_basis', sa.String(), server_default='from_creation', nullable=False),
    sa.Column('basis_date', sa.Date(), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('storage_ref', sa.String(), nullable=True),
    sa.Column('immutable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_firm_id'), 'records', ['firm_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('related_client_id', sa.UUID(), nullable=True),
    sa.Column('related_matter_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deadline_basis', sa.String(), nullable=True),
    sa.Column('lpp_claimed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lpp_form_ref', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lodged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lodged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['lodged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['related_matter_id'], ['matters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_firm_id'), 'reports', ['firm_id'], unique=False)
    op.create_table('report_decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('reasonable_grounds', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_decision_logs_firm_id'), 'report_decision_logs', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_decision_logs_firm_id'), table_name='report_decision_logs')
    op.drop_table('report_decision_logs')
    op.drop_index(op.f('ix_reports_firm_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_records_firm_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
