"""onboarding schema and corrected data model

Revision ID: cbb64de0267d
Revises: 
Create Date: 2026-06-01 06:41:14.526801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb64de0267d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('firm_size', sa.String(), nullable=True),
    sa.Column('practice_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('austrac_enrolment_number', sa.String(), nullable=True),
    sa.Column('enrolment_status', sa.String(), server_default='not_enrolled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_action_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('human_action_type', sa.String(), nullable=True),
    sa.Column('human_action_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_action_taken_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_firm_id'), 'agent_tasks', ['firm_id'], unique=False)
    op.create_table('firm_risk_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('overall_risk_rating', sa.String(), server_default='unassessed', nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_risk_states_firm_id'), 'firm_risk_states', ['firm_id'], unique=True)
    op.create_table('governance_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('action_label', sa.String(), server_default='Review and approve', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_approvals_firm_id'), 'governance_approvals', ['firm_id'], unique=False)
    op.create_table('review_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_required_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_triggers_firm_id'), 'review_triggers', ['firm_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='admin', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_firm_id'), 'audit_log', ['firm_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('compliance_deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('deadline_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_deadlines_firm_id'), 'compliance_deadlines', ['firm_id'], unique=False)
    op.create_table('governance_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('appointed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appointed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_roles_firm_id'), 'governance_roles', ['firm_id'], unique=False)
    op.create_index(op.f('ix_governance_roles_user_id'), 'governance_roles', ['user_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('overall_risk_rating', sa.String(), server_default='unassessed', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('next_review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_name', sa.String(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_firm_id'), 'risk_assessments', ['firm_id'], unique=False)
    op.create_table('risk_assessment_countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('inherent_risk_rating', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_countries_firm_id'), 'risk_assessment_countries', ['firm_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_countries_risk_assessment_id'), 'risk_assessment_countries', ['risk_assessment_id'], unique=False)
    op.create_table('risk_assessment_customer_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('customer_type', sa.String(), nullable=False),
    sa.Column('inherent_risk_rating', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_customer_types_firm_id'), 'risk_assessment_customer_types', ['firm_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_customer_types_risk_assessment_id'), 'risk_assessment_customer_types', ['risk_assessment_id'], unique=False)
    op.create_table('risk_assessment_delivery_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('inherent_risk_rating', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_delivery_channels_firm_id'), 'risk_assessment_delivery_channels', ['firm_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_delivery_channels_risk_assessment_id'), 'risk_assessment_delivery_channels', ['risk_assessment_id'], unique=False)
    op.create_table('risk_assessment_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_assessment_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('designated_service_type', sa.String(), nullable=False),
    sa.Column('inherent_risk_rating', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessment_services_firm_id'), 'risk_assessment_services', ['firm_id'], unique=False)
    op.create_index(op.f('ix_risk_assessment_services_risk_assessment_id'), 'risk_assessment_services', ['risk_assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessment_services_risk_assessment_id'), table_name='risk_assessment_services')
    op.drop_index(op.f('ix_risk_assessment_services_firm_id'), table_name='risk_assessment_services')
    op.drop_table('risk_assessment_services')
    op.drop_index(op.f('ix_risk_assessment_delivery_channels_risk_assessment_id'), table_name='risk_assessment_delivery_channels')
    op.drop_index(op.f('ix_risk_assessment_delivery_channels_firm_id'), table_name='risk_assessment_delivery_channels')
    op.drop_table('risk_assessment_delivery_channels')
    op.drop_index(op.f('ix_risk_assessment_customer_types_risk_assessment_id'), table_name='risk_assessment_customer_types')
    op.drop_index(op.f('ix_risk_assessment_customer_types_firm_id'), table_name='risk_assessment_customer_types')
    op.drop_table('risk_assessment_customer_types')
    op.drop_index(op.f('ix_risk_assessment_countries_risk_assessment_id'), table_name='risk_assessment_countries')
    op.drop_index(op.f('ix_risk_assessment_countries_firm_id'), table_name='risk_assessment_countries')
    op.drop_table('risk_assessment_countries')
    op.drop_index(op.f('ix_risk_assessments_firm_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_governance_roles_user_id'), table_name='governance_roles')
    op.drop_index(op.f('ix_governance_roles_firm_id'), table_name='governance_roles')
    op.drop_table('governance_roles')
    op.drop_index(op.f('ix_compliance_deadlines_firm_id'), table_name='compliance_deadlines')
    op.drop_table('compliance_deadlines')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_firm_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_review_triggers_firm_id'), table_name='review_triggers')
    op.drop_table('review_triggers')
    op.drop_index(op.f('ix_governance_approvals_firm_id'), table_name='governance_approvals')
    op.drop_table('governance_approvals')
    op.drop_index(op.f('ix_firm_risk_states_firm_id'), table_name='firm_risk_states')
    op.drop_table('firm_risk_states')
    op.drop_index(op.f('ix_agent_tasks_firm_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_table('firms')
    # ### end Alembic commands ###
